### PR TITLE
Set super as the Overlay key

### LINKED ISSUE #3: Set Super as the Overlay key
Original: https://github.com/elementary/applications-menu/issues/33.

Change the default applications menu shortcut from "Super+Space" to "Super".
This can be done by setting those two keys:

`org.gnome.mutter overlay-key` to `'Super_L'` (possibly adding `'Super_R'` also)
`org.pantheon.desktop.gala.behavior overlay-action` `'wingpanel --toggle-indicator=app-launcher'`

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #3

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Will this not work with the right hand super as well?

**Comment by danrabbit** [comment]
I'm gonna throw my :-1: here because as some of the comments on #3 point out, I've experienced a number of accidentally triggers since adding this. Originally I thought, "Sure, shouldn't effect me", but it turns out it's annoying.

**Comment by cassidyjames** [comment]
@lewisgoddard we could also add it :man_shrugging:

**Comment by danrabbit** [comment]
@cassidyjames can you remove the overlay action here and then we can add back the default as the shortcut overlay once it lands in the ISO?

**Comment by cassidyjames** [comment]
@danrabbit done. We should probably add the right super key here as well before we merge.

**Comment by cassidyjames** [comment]
@lewisgoddard @danrabbit the GSettings key is just a string, not a string array. So only one key is accepted.

**Pull request merged**
