### PR TITLE
Make GSettings Overrides specific to Pantheon session

### LINKED ISSUE #81: Change overrides to be specific to the Pantheon session
This is a feature in GSettings/GLib in Ubuntu as of 17.10 (and is pending upstream merging): you can append `:sessionname` to the end of the override and have it only apply to that session. This is used in production in Ubuntu and Pop!_OS to not conflict with one anothers' sessions, and to keep the stock GNOME session clean as well.

If this works and doesn't change anything negatively for us, it would probably be more kosher.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58654175-change-overrides-to-be-specific-to-the-pantheon-session?utm_campaign=plugin&utm_content=tracker%2F74974394&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F74974394&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by worldofpeace**
Fixes #81

This is a really nice feature and makes these overrides much better to use as they won't conflict with default GNOME specifically.

### CODE REVIEW

**Comment by cassidyjames** [comment]
@worldofpeace ha, I thought we did this long ago for some reason. Seeing as this is for default settings, do you know the best way to test this before merging?

**Comment by worldofpeace** [comment]
> @worldofpeace ha, I thought we did this long ago for some reason. Seeing as this is for default settings, do you know the best way to test this before merging?

Yes, I do know the best way to test this.

https://github.com/elementary/default-settings/pull/97#pullrequestreview-168914317
> debuild -us -uc -j -b
> sudo dpkg -i ../*.deb

And I guess a reboot is a safe way to check if everything is in order.

If it's a fail you'll likely notice right away the session **and greeter** looking very very broken.
If that's not the case you can assume it is a success, but you could also check the default value of a certain key https://github.com/elementary/default-settings/blob/master/overrides/default-settings.gschema.override.in#L11 and see if it's the same as specified in the override.

**Comment by cassidyjames** [comment]
@worldofpeace ah so I see an issue here: the greeter and installer sessions are not considered Pantheon, I think. When I apply this, the session works fine but the greeter session has the wrong fonts and icons. I assume the same thing would be true for the Installer session.

**Comment by worldofpeace** [comment]
> @worldofpeace ah so I see an issue here: the greeter and installer sessions are not considered Pantheon, I think. When I apply this, the session works fine but the greeter session has the wrong fonts and icons. I assume the same thing would be true for the Installer session.

Perhaps I can make glib happy enough with the greeter and installer by setting `XDG_CURRENT_DESKTOP` to pantheon.
example https://gitlab.gnome.org/GNOME/glib/-/blob/master/gio/tests/gsettings.c#L2797

**Comment by worldofpeace** [comment]
> > @worldofpeace ah so I see an issue here: the greeter and installer sessions are not considered Pantheon, I think. When I apply this, the session works fine but the greeter session has the wrong fonts and icons. I assume the same thing would be true for the Installer session.
> 
> Perhaps I can make glib happy enough with the greeter and installer by setting `XDG_CURRENT_DESKTOP` to pantheon.
> example https://gitlab.gnome.org/GNOME/glib/-/blob/master/gio/tests/gsettings.c#L2797

I tried this and it didn't work :frowning_face: It's possible that I just didn't do it right (I tried to put it in main of greeter), but I not really sure to do about the greeter and installer.

**Comment by worldofpeace** [comment]
Ugh, I feel like this pull request is cursed :rofl:

**Comment by davidmhewitt** [comment]
I've opened a PR for greeter that I've tested works in conjunction with this branch. I've also opened one for installer that I believe will work but haven't had the chance to test yet as I'm working on my Pinebook Pro and we don't build distinst/installer for ARM.

**Comment by worldofpeace** [comment]
I can test with both since I believe I have the installer packaged somewhere

**Comment by decathorpe** [comment]
I've tested this on Fedora, and I can confirm that it works as expected (overrides applying to the elementary greeter and Pantheon session, but not to, for example, a GNOME session). The elementary installer is not packaged for Fedora yet, so I was not able to test this there, though.

**Review by danrabbit — APPROVED** [review]
YOLO

**Comment by worldofpeace** [comment]
@danrabbit was like :shipit:

**Pull request merged**
