### PR TITLE
Drop Qt style overrides

### LINKED ISSUE #286: adwaita-qt is no longer maintained
Currently we have these lines:

https://github.com/elementary/default-settings/blob/37ef6062a8651875dd9d927c5730155c8b26e953/debian/control#L14

https://github.com/elementary/default-settings/blob/37ef6062a8651875dd9d927c5730155c8b26e953/profile.d/qt-style-override.sh#L1

The motivation of these lines are in https://github.com/elementary/default-settings/issues/88.

With a [decision](https://fedoraproject.org/wiki/Changes/NoCustomQtThemingForWorkstation) made in Fedora and https://github.com/FedoraQt/adwaita-qt/commit/0a774368916def5c9889de50f3323dec11de781e, the adwaita-qt project is no longer maintained and I don't aware of 1:1 replacement right now. In NixOS we are currently reducing the use of adwaita-qt & qgnomeplatform in desktops and might drop it when it FTBFS but I am not sure what will be the best action for Pantheon.

### LINKED ISSUE #298: qt-qpa-platformtheme.sh is gtk3 not gtk4 ?
### What Happened?

EOS uses GTK4 but it is always GTK3 which is defined in the default environment

in https://github.com/elementary/default-settings/blob/master/profile.d/qt-qpa-platformtheme.sh
export QT_QPA_PLATFORMTHEME=gtk3

impact qt app dont use correct theme.

### Steps to Reproduce

open https://github.com/elementary/default-settings/blob/master/profile.d/qt-qpa-platformtheme.sh
or /etc/profile.d/qt-qpa-platformtheme.sh

### Expected Behavior

define the variable in phase with the version used.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #286 
Fixes #298 
Closes #304

### CODE REVIEW

**Comment by bobby285271** [comment]
Hmmm I actually still kept "qt5-gtk-platformtheme" (we don't split packages so `libqgtk3.so` is actually provided by [`qt5.qtbase`](https://invent.kde.org/qt/qt/qtbase)) and `QT_QPA_PLATFORMTHEME=gtk3` in NixOS Pantheon because [Qt does not likely know Pantheon](https://invent.kde.org/qt/qt/qtbase/-/blob/6.6/src/gui/platform/unix/qgenericunixthemes.cpp#L1330) and I have the impression this can probably affect the use of native GTK dialogs, but yeah we don't have qgnomeplatform or adwaita-qt pre-installed now. I don't know how qgnomeplatform is used in elementary, but I think https://github.com/FedoraQt/QGnomePlatform/commit/d86d6baab74c3e69094083715ffef4aef2e516dd will make it stop using the gtk3 key :thinking:

**Comment by danirabbit** [comment]
We don't ship anything Qt and as far as I can tell, Qt Flatpak apps aren't using any kind of Gtk style so I don't think this is ever used

**Comment by TomiOhl** [comment]
One relatively widely-used application that is affected by this setting is Telegram desktop (official non-flatpak build). See a related issue: https://github.com/telegramdesktop/tdesktop/issues/26370
What I did to try to test this:
- unset QT_QPA_PLATFORMTHEME, unset QT_STYLE_OVERRIDE
- launch tdesktop with the system set to both light and dark mode
- switched light/dark mode while the app is running
- opened the file chooser
Everything seems to look fine and work as before, so as long as unsetting that env is equivalent to testing the changes in this PR, tdesktop won't break 🎉 
(QT_STYLE_OVERRIDE=adwaita was an invalid value anyways according to tdesktop's logs)

**Comment by danirabbit** [comment]
@bobby285271 any further thoughts on this? or requested changes?

**Comment by bobby285271** [comment]
Nope, we have some NixOS-specific way to declare session environment variables and I don't think I can test this PR on NixOS, otherwise I have no objections :-)

**Pull request merged**
