### PR TITLE
Block tracking ads by default

### LINKED ISSUE #126: Epiphany should block trackers and related advertisements
Forgive me for filing this bug here as I couldn't find any repo for the slightly-modified Epiphany being shipped by elementary.

For a company with a strong stance on privacy by design, it is somewhat strange to see the default elementary browser shipping with the setting of "Block advertisements" and "Block trackers" turned off. Even upstream has the settings on, but elementary has explicitly turned it off it seems (?).
screenshot from 2019-02-27 07-10-48

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/70660762-epiphany-should-block-trackers-and-related-advertisements?utm_campaign=plugin&utm_content=tracker%2F74974394&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F74974394&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by uncertainquark**
Out of the box, Firefox, GNOME Epiphany and Brave block tracking ads, for enhanced privacy. Safari is going to join the list with the new WekKit tracking protection spec. It'd be great for elementary's Epiphany to ship a privacy enhancing default that also saves a lot of annoyance while browsing on the web. This PR fixes #126. 

Firefox hasn't shown any functional regression since over a year of enabling the setting there. And in my limited testing, Epiphany is working fine too with some popular sites.

### CODE REVIEW

**Comment by cassidyjames** [comment]
We intentionally did not turn on the ad blocker because we've been told it makes performance worse, plus it's a heavy-handed ban-hammer, taking revenue away from sites with legitimate, safe ads. We didn't feel it was appropriate for us to make that decision on the platform level.

**Comment by uncertainquark** [comment]
I thought the blocking took place explicitly for tracking ads based on a list like Disconnect?

**Comment by mcatanzaro** [comment]
> We intentionally did not turn on the ad blocker because we've been told it makes performance worse,

It did prior to 3.34, although memory usage was probably a larger concern than performance. Nowadays we use WebKit's built-in adblocker, which is very fast and memory-efficient.

> I thought the blocking took place explicitly for tracking ads based on a list like Disconnect?

No, it just blocks all ads.

Prior to 3.34, we had a separate EasyPrivacy blocklist, but that doesn't exist in JSON format so we don't use it anymore.

**Comment by cassidyjames** [comment]
Still have to decide if this is worth it, though:

>it's a heavy-handed ban-hammer, taking revenue away from sites with legitimate, safe ads. We didn't feel it was appropriate for us to make that decision on the platform level.

**Comment by jeremypw** [comment]
@uncertainquark @cassidyjames Converting to draft as has conflicts and undecided design issues. Please feel free to close or reopen for review after fixing conflicts as desired.

**Comment by danrabbit** [comment]
It looks like GNOME Web has the ad blocker enabled by default these days. It's not clear overrides here have any effect on the Flatpak.

Closing since we probably should move any default settings changes to https://github.com/elementary/browser anyways

**Comment by mcatanzaro** [comment]
The adblocker has been enabled by default for nearly a decade. ;)

**Comment by danrabbit** [comment]
@mcatanzaro I meant in elementary OS specifically 😅 It probably has been since we migrated to the Flatpak

**Pull request closed without merging**
