### PR TITLE
Enable ambient and idle-dim in g-s-d power

### PR DESCRIPTION
**Pull request by worldofpeace**
These are just powersettings that are defaults
in g-s-d that appear to be completely sane.

### CODE REVIEW

**Comment by worldofpeace** [comment]
Cross-referencing discussion at https://github.com/elementary/default-settings/pull/138#discussion_r331731533

**Comment by worldofpeace** [comment]
I'm not sure how much power is saved by dimming during the idle period, but I do know several mobile os's have the feature built-in.

**Comment by worldofpeace** [comment]
Hmm, it appears that Pantheon manages dpms defaults entirely separate from g-s-d https://github.com/elementary/os-patches/commit/af897c5788231d4f76dd2f00aaaa533905109e0e. So idle-dim is a completely separate thing, which will probably require some sort of option in the power switchboard plug.

**Comment by worldofpeace** [comment]
I'm going to close this, as I expect the non-response is just because it's not a great proposal.

**Comment by danrabbit** [comment]
Can you reopen this? I'd like to add it to the 6.0 milestone and make sure it gets discussed for the next release :)

**Comment by worldofpeace** [comment]
> Can you reopen this? I'd like to add it to the 6.0 milestone and make sure it gets discussed for the next release :)

Sorry, I forgot to mention that I need to narrow the scope of some of my contributions.
The patch is still available at https://patch-diff.githubusercontent.com/raw/elementary/default-settings/pull/140.patch. All other open patches I'm still pursuing though.
Anyways, thanks @danrabbit @cassidyjames for your clear communications.
I do appreciate them.

**Pull request closed without merging**
